import { DEFAULT_CATEGORY_NAME } from "../lib/categories";

// Five example answers per question, in French — shown to players as a
// rotating placeholder hint, and used server-side as a bot's answer pool
// (lib/db/bots.ts). English versions are generated from these at seed time
// via DeepL rather than authored twice (see prisma/seed.ts).
export const PLACEHOLDERS_FR: Record<string, string[][]> = {
  [DEFAULT_CATEGORY_NAME]: [
    ["un pingouin pirate", "une sorcière fatiguée", "un facteur maladroit", "une licorne comptable", "un robot amoureux"],
    ["dans un sous-marin", "sous un pont", "au fond d'un placard", "sur la lune", "dans une supérette"],
    ["il dansait la salsa", "elle comptait des moutons", "il réparait un grille-pain", "elle apprenait le yodel", "il faisait la sieste"],
    ["un fantôme timide", "sa propre grand-mère", "un poulpe philosophe", "un ancien président", "une abeille parlante"],
    ["dans un ascenseur bloqué", "au sommet d'un volcan", "dans une file d'attente", "sous une table de mariage", "au rayon des surgelés"],
    ["un voyage sans retour", "une part de gâteau", "de devenir pirate", "un duel au fromage", "de garder un secret"],
    ["une télécommande magique", "un chapeau qui parle", "une carte au trésor", "un œuf géant", "une clé sans serrure"],
    ["dans une dimension parallèle", "au fond de l'océan", "chez le voisin bizarre", "tout droit en prison", "dans le passé"],
    ["un chat autoritaire", "la police locale", "leur propre reflet", "un gardien endormi", "une mamie déterminée"],
    ["ils ont chanté très fort", "ils ont supplié le chat", "ils ont fait semblant de dormir", "ils ont tout cassé", "ils ont négocié un fromage"],
    ["de retour à la maison", "sur une plage déserte", "en prison", "au restaurant du coin", "nulle part vraiment"],
    ["on ne fait plus ça", "je le referais bien", "qui a pris mon sandwich", "plus jamais de lundi", "c'était vraiment nécessaire ça"],
  ],
  "😂 Funny": [
    ["un clown fatigué", "le chien du voisin", "une mamie déchaînée", "le stagiaire du bureau", "un perroquet moqueur"],
    ["en pleine réunion", "au mariage de sa sœur", "devant toute la classe", "dans l'ascenseur du bureau", "à la caisse du supermarché"],
    ["un costume de banane", "des chaussettes dépareillées géantes", "un chapeau en carton", "une cape trop courte", "des lunettes de piscine"],
    ["le videur de la boîte", "sa propre grand-mère", "le prof de maths", "un inconnu dans le bus", "le chat, apparemment"],
    ["sous la table", "dans les toilettes", "derrière un pilier", "dans le coffre de la voiture", "au fond du jardin"],
    ["un couinement de canard", "un rot monumental", "un cri de dinosaure", "un bruit de trombone", "un hoquet interminable"],
    ["le petit frère", "la caméra de surveillance", "un touriste au hasard", "le chat sur l'étagère", "un drone égaré"],
    ["tout le monde pleurait de rire", "le chien s'y est mis aussi", "même le videur a craqué", "la vidéo est devenue virale", "personne n'a pu se relever"],
  ],
  "🔥 Chaos": [
    ["un stagiaire terrifié", "une mamie increvable", "un clown sans limites", "un chat maléfique", "un livreur pressé"],
    ["ils allument un barbecue en intérieur", "ils font du vélo sur le toit", "ils libèrent tous les hamsters", "ils repeignent la maison du voisin", "ils lancent un feu d'artifice dedans"],
    ["en plein supermarché", "sur l'autoroute", "dans un mariage", "au beau milieu du bureau", "dans un ascenseur bondé"],
    ["une chèvre en furie", "un raton laveur voleur", "un paon prétentieux", "un serpent égaré", "une nuée de pigeons"],
    ["le stagiaire, encore lui", "un pompier maladroit", "la mamie increvable", "un influenceur en direct", "le chat, forcément"],
    ["le four à micro-ondes", "une canalisation", "le gâteau d'anniversaire", "le barbecue", "une bouteille de soda"],
    ["le maire porte une perruque", "le gâteau était périmé", "personne ne sait vraiment cuisiner", "le chien comprend le français", "c'était un plan depuis le début"],
    ["le chat, comme toujours", "le stagiaire innocent", "un courant d'air mystérieux", "personne, officiellement", "le voisin du dessus"],
    ["courez", "ce n'est pas moi", "appelez les pompiers", "qui a fait ça", "au secours"],
    ["tout le monde nettoie en silence", "avec une facture salée", "dans un fou rire général", "personne ne s'en souvient vraiment", "par une nouvelle catastrophe"],
  ],
  "👫 Friends": [
    ["le plus tête en l'air", "celui qui organise tout", "la plus discrète du groupe", "le rigolo de service", "celle qui arrive toujours en retard"],
    ["coincés dans une file d'attente", "perdus en pleine forêt", "au fast-food du coin", "sur le toit d'un immeuble", "dans une voiture en panne"],
    ["ils cherchent les clés perdues", "ils répètent une chorégraphie", "ils font un pari stupide", "ils tentent de cuisiner", "ils planifient un mauvais coup"],
    ["un ex qu'on évite", "le cousin bizarre", "une connaissance du lycée", "le meilleur ami du chien", "quelqu'un qu'ils ne connaissent pas"],
    ["le plus discret du groupe", "leur propre téléphone", "un post sur les réseaux", "le cousin bavard", "le silence gênant"],
    ["un inconnu généreux", "la mamie du quartier", "leur bon sens, finalement", "un chauffeur de taxi", "un coup de chance énorme"],
    ["ils appellent la mauvaise personne", "le pantalon craque en public", "ils chantent trop fort", "le message part au mauvais groupe", "tout le monde les regarde"],
    ["personne, par miracle", "le plus innocent du groupe", "le mauvais suspect", "leur propre plan", "tout le groupe, en rigolant"],
    ["on ne recommence jamais ça", "c'était quand même génial", "qui a eu cette idée", "il fallait filmer ça", "on garde ça secret"],
    ["la photo ratée", "le fou rire sans fin", "cette nuit impossible à expliquer", "le plan qui a presque marché", "cette phrase culte du groupe"],
  ],
  "❤️ Romance": [
    ["le livreur de pizza", "une inconnue au café", "le nouveau collègue", "la bibliothécaire timide", "un touriste perdu"],
    ["à la laverie automatique", "dans une file d'attente", "lors d'un mariage", "sur un quai de gare", "au rayon des pâtes"],
    ["un bouquet de pissenlits", "une chanson maladroite", "un carnet de dessins", "un café encore chaud", "une lettre écrite à la main"],
    ["le voisin discret", "la meilleure amie, par erreur", "un admirateur anonyme", "le collègue timide", "une grand-mère romantique"],
    ["dans un vieux cinéma", "sur un banc public", "au marché du dimanche", "devant un feu de camp", "dans une pizzeria bondée"],
    ["un malentendu ridicule", "la distance", "un ex jaloux", "un déménagement soudain", "un secret de famille"],
    ["le témoin du mariage", "la meilleure amie", "un parfait inconnu", "le père, en larmes", "le facteur, sans le vouloir"],
    ["par un mariage improvisé", "en simples amis", "dans un grand fou rire", "avec une lettre d'adieu", "personne ne le sait vraiment"],
  ],
  "🧙 Fantasy": [
    ["un forgeron maladroit", "une princesse rebelle", "un dragon végétarien", "un elfe distrait", "un fermier sans histoire"],
    ["au sommet des nuages", "sous une montagne endormie", "de l'autre côté du miroir", "au fond d'un puits", "derrière une porte oubliée"],
    ["un dragon peureux", "une licorne grincheuse", "un troll bibliothécaire", "un phénix enrhumé", "une fée sans magie"],
    ["un roi déchu", "une sorcière solitaire", "un simple berger", "un miroir maudit", "un enfant sans le savoir"],
    ["au fond d'un lac gelé", "dans le ventre d'un dragon", "sous le trône du roi", "dans une bibliothèque oubliée", "derrière une cascade"],
    ["un sort de vérité", "une malédiction de silence", "un charme d'invisibilité", "un sort raté", "une prophétie ancienne"],
    ["le roi lui-même", "une armée d'ombres", "leur propre mentor", "un dragon endormi trop tôt", "la prophétie elle-même"],
    ["par un sacrifice inattendu", "dans une paix fragile", "avec un nouveau roi", "par un simple éclat de rire", "personne ne s'en souvient vraiment"],
  ],
  "🚀 Sci-Fi": [
    ["une intelligence artificielle bavarde", "un capitaine somnolent", "un stagiaire terrifié", "un robot de ménage", "personne, en fait"],
    ["sur une lune inconnue", "au milieu d'un champ de blé", "dans un océan extraterrestre", "sur une station abandonnée", "en plein Paris, par erreur"],
    ["un portail instable", "une machine à traduire les pensées", "un moteur alimenté par le rire", "une bibliothèque vivante", "un objet qui efface le temps"],
    ["le radar défaillant", "un stagiaire distrait", "l'intelligence artificielle du bord", "un enfant avec une radio", "un satellite oublié"],
    ["dans les moteurs du vaisseau", "sous la surface glacée", "au cœur de l'équipage", "dans le signal lui-même", "depuis le tout début"],
    ["un simple trombone", "une combinaison rafistolée", "un vieux talkie-walkie", "un robot aspirateur reprogrammé", "de la bande adhésive spatiale"],
    ["l'intelligence artificielle rebelle", "un passager clandestin", "le stagiaire, enfin utile", "un virus informatique", "personne, il dérive"],
    ["par une blague au bon moment", "grâce à un trombone", "par pur hasard", "avec l'aide d'un robot ménager", "par une négociation improbable"],
  ],
  "🎉 Party": [
    ["une mamie déchaînée", "un voisin discret", "un stagiaire trop motivé", "personne, ça s'est fait tout seul", "le chat du quartier, apparemment"],
    ["sur un toit d'immeuble", "dans un garage", "au fond d'un jardin", "dans une piscine vide", "chez le mauvais voisin"],
    ["un costume de dinosaure", "une toge en papier alu", "un pyjama de licorne", "un smoking et des tongs", "une cape et rien d'autre"],
    ["la grand-mère du marié", "le patron, sans prévenir", "un inconnu très motivé", "le chien de la maison", "tout le monde, finalement"],
    ["au pire moment possible", "juste avant le discours", "en pleine chorégraphie", "quand les voisins ont appelé", "sans aucune raison"],
    ["le canapé irrécupérable", "une fenêtre cassée", "le gâteau écrasé au sol", "une flaque mystérieuse", "la platine disparue"],
    ["le plus discret de tous", "la personne qu'on attendait le moins", "le chat, comme toujours", "deux inconnus devenus amis", "personne ne s'en souvient"],
    ["dans un fou rire épuisé", "avec un grand ménage forcé", "au fast-food du coin", "tout le monde endormi par terre", "avec une nouvelle légende de quartier"],
  ],
  "🎨 Random": [
    ["un inconnu sur son canapé", "lui-même, sur un toit", "un chat dans le four", "elle, au beau milieu d'un champ", "son voisin, dans son propre lit"],
    ["dans une file d'attente", "au fond d'un ascenseur", "devant un distributeur cassé", "sur un parking désert", "dans une salle d'attente"],
    ["une télécommande sans piles", "un chapeau qui chante", "une clé sans porte", "un œuf qui tremble", "une boîte qui rit"],
    ["le plus raisonnable du groupe", "un inconnu très convaincant", "eux-mêmes, sans réfléchir", "un panneau publicitaire, apparemment", "le hasard, encore une fois"],
    ["au rayon des conserves", "dans une cabine téléphonique", "juste après le feu rouge", "au beau milieu d'un silence", "sur le trottoir d'en face"],
    ["ne jamais suivre un inconnu", "toujours vérifier avant de signer", "ne pas nourrir les pigeons", "ne jamais dire oui trop vite", "toujours compter ses affaires"],
    ["le plus malin du groupe", "la personne qui posait les questions", "eux-mêmes, évidemment", "le témoin silencieux", "tout le monde en même temps"],
    ["personne ne l'a vraiment cru", "avec une explication encore plus folle", "dans un grand éclat de rire", "sans aucune explication du tout", "exactement comme on pouvait s'y attendre"],
  ],
};
